-- fill genres
INSERT INTO PUBLIC.GENRES (NAME)
	VALUES ('Comedy');
INSERT INTO PUBLIC.GENRES (NAME)
	VALUES ('Horror');
INSERT INTO PUBLIC.GENRES (NAME)
	VALUES ('Detective');

-- fill ratings
INSERT INTO PUBLIC.AGE_RESTRICTION_RATINGS (RATING_BLOCK,DESCRIPTION)
	VALUES ('GA','General Audience; Suitable for all ages.');
INSERT INTO PUBLIC.AGE_RESTRICTION_RATINGS (RATING_BLOCK,DESCRIPTION)
	VALUES ('PG','Parental Guidance.');
INSERT INTO PUBLIC.AGE_RESTRICTION_RATINGS (RATING_BLOCK,DESCRIPTION)
	VALUES ('PG13','Parental Guidance 13; suitable for 13 years and older.');
INSERT INTO PUBLIC.AGE_RESTRICTION_RATINGS (RATING_BLOCK,DESCRIPTION)
	VALUES ('R','Suitable for 18 years and older.');
INSERT INTO PUBLIC.AGE_RESTRICTION_RATINGS (RATING_BLOCK,DESCRIPTION)
	VALUES ('A','Adult Only; No-one under 18 admitted.');

